title: Bytes & Bridges # name of the site
author: Sagar # name of site's author
email:  # email of site's author
url: https://sagrd.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Hi, I'm Sagar Dhungel, Data Science and Engineering Consultant. Join me on this blog(rss) as we explore topics in Machine Learning, Analytics and Data Engineering.
permalink: /:slug.md.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
goat_counter: "sagrd" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "Home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  zettels:
    output: true

